--------------------------------------------------------------------------------
-- V1 - DDL DAS TABELAS DO DOMINIO (TUTOR, VETERINARIO, PET, CONSULTA, USUARIO)
--------------------------------------------------------------------------------

CREATE TABLE TUTOR (
    ID_TUTOR        NUMBER(6)       NOT NULL,
    NOME            VARCHAR2(100)   NOT NULL,
    CPF             VARCHAR2(14)    NOT NULL,
    TELEFONE        VARCHAR2(20),
    EMAIL           VARCHAR2(100),
    ENDERECO        VARCHAR2(200),
    DATA_CADASTRO   DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT KV_PK_TUTOR PRIMARY KEY (ID_TUTOR),
    CONSTRAINT KV_UQ_TUTOR_CPF UNIQUE (CPF)
);

CREATE TABLE VETERINARIO (
    ID_VETERINARIO  NUMBER(6)       NOT NULL,
    NOME            VARCHAR2(100)   NOT NULL,
    CRMV            VARCHAR2(20)    NOT NULL,
    ESPECIALIDADE   VARCHAR2(60),
    TELEFONE        VARCHAR2(20),
    EMAIL           VARCHAR2(100),
    CONSTRAINT KV_PK_VET PRIMARY KEY (ID_VETERINARIO),
    CONSTRAINT KV_UQ_VET_CRMV UNIQUE (CRMV)
);

CREATE TABLE PET (
    ID_PET          NUMBER(6)       NOT NULL,
    NOME            VARCHAR2(60)    NOT NULL,
    ESPECIE         VARCHAR2(30)    NOT NULL,
    RACA            VARCHAR2(60),
    DATA_NASCIMENTO DATE            NOT NULL,
    SEXO            CHAR(1)         NOT NULL,
    ID_TUTOR        NUMBER(6)       NOT NULL,
    CONSTRAINT KV_PK_PET PRIMARY KEY (ID_PET),
    CONSTRAINT KV_CK_PET_SEXO CHECK (SEXO IN ('M','F')),
    CONSTRAINT KV_FK_PET_TUTOR FOREIGN KEY (ID_TUTOR) REFERENCES TUTOR(ID_TUTOR)
);

CREATE TABLE CONSULTA (
    ID_CONSULTA     NUMBER(6)       NOT NULL,
    ID_PET          NUMBER(6)       NOT NULL,
    ID_VETERINARIO  NUMBER(6)       NOT NULL,
    DATA_CONSULTA   DATE            NOT NULL,
    TIPO_CONSULTA   VARCHAR2(40)    NOT NULL,
    DIAGNOSTICO     VARCHAR2(400),
    STATUS          VARCHAR2(20)    DEFAULT 'AGENDADA' NOT NULL,
    CONSTRAINT KV_PK_CONSULTA PRIMARY KEY (ID_CONSULTA),
    CONSTRAINT KV_CK_CONS_STATUS CHECK (STATUS IN ('AGENDADA','REALIZADA','CANCELADA')),
    CONSTRAINT KV_FK_CONS_PET FOREIGN KEY (ID_PET) REFERENCES PET(ID_PET),
    CONSTRAINT KV_FK_CONS_VET FOREIGN KEY (ID_VETERINARIO) REFERENCES VETERINARIO(ID_VETERINARIO)
);

-- ID_TUTOR e obrigatorio quando PERFIL=TUTOR e proibido quando PERFIL=VETERINARIO,
-- espelhando a regra de negocio da Tarefa 5 direto no schema.
CREATE TABLE USUARIO (
    ID_USUARIO      NUMBER(6)       NOT NULL,
    USERNAME        VARCHAR2(60)    NOT NULL,
    SENHA           VARCHAR2(100)   NOT NULL,
    PERFIL          VARCHAR2(20)    NOT NULL,
    ID_TUTOR        NUMBER(6),
    CONSTRAINT KV_PK_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT KV_UQ_USUARIO_USERNAME UNIQUE (USERNAME),
    CONSTRAINT KV_CK_USU_PERFIL CHECK (PERFIL IN ('TUTOR','VETERINARIO')),
    CONSTRAINT KV_CK_USU_TUTOR CHECK (
        (PERFIL = 'TUTOR' AND ID_TUTOR IS NOT NULL) OR
        (PERFIL = 'VETERINARIO' AND ID_TUTOR IS NULL)
    ),
    CONSTRAINT KV_FK_USU_TUTOR FOREIGN KEY (ID_TUTOR) REFERENCES TUTOR(ID_TUTOR)
);

--------------------------------------------------------------------------------
-- SEQUENCES PARA GERACAO DE PK
-- Os seeds de V2/V3 usam IDs baixos manualmente; as sequences comecam em 11
-- (100 para USUARIO, que tem menos seed) para nao colidir com eles.
--------------------------------------------------------------------------------

CREATE SEQUENCE SEQ_TUTOR       START WITH 11  INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_VETERINARIO START WITH 11  INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PET         START WITH 11  INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CONSULTA    START WITH 11  INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_USUARIO     START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
