$RG        = "rg-kuravet-rm563620"
$LOCAL     = "mexicocentral"
$PLANO     = "plan-kuravet-rm563620"
$SKU       = "B1"
$WEBAPP    = "kuravet-rm563620"
$SQLSERVER = "sqlserver-kuravet-rm563620"
$SQLDB     = "bd_kuravet"
$SQLUSER   = "kuravetadmin"

$SQLPASS = Read-Host "Senha do administrador do SQL Server"